#!/bin/bash
/usr/local/bin/mise trust /workspaces/dotfiles/mise.toml && /usr/local/bin/mise install
/usr/local/bin/mise trust ~/.local/share/chezmoi

# Installing VIM
sudo apt update && sudo apt install vim -y
